#!/bin/bash

usage="Usage: blk [ info | stake | latest | dust ] \n \n
	info: Check basic info. \n
	stake: Enables staking; Passes password without storing it in memory. \n
	latest: Compares latest block with the ViptocoinNL hosted block explorer. \n
	dust: Prunes dust from wallet. Dust is defined as less than .0001VCC. Requires jq. \n"

vccc='/usr/local/bin/viptocoin-cli -datadir=/var/lib/.viptocoin/'

case $1 in

info )
	$vccc getwalletinfo | egrep "balance|staked_balance|txcount|unconfirmed_balance|immature_balance|total_balance";
	$vccc getnetworkinfo | egrep "subversion|connections";
	$vccc getinfo | egrep "blocks";
	$vccc getblockchaininfo | egrep "best";
	$vccc getstakinginfo | egrep "enabled|staking|netstakeweight|expectedtime";
;;	

stake )
	echo 'enter Viptocoin Password'
	read -s VCCPW
	$vccc walletpassphrase $VCCPW 99999999 true
	VCCPW=null
;;

latest )
	latest=$($vccc  getblockcount) && \
	    blacksight=$(curl -s https://node.viptocoin.com/insight-api/block-index/$latest? |  cut -d '"' -f4) && \
	    viptocoin=$($vccc  getblockhash $latest) && \
	    diff -sy --label Local <(echo $viptocoin) --label Explorer <(echo $blacksight)
;;

dust )
	IFS=$'\n';

	 /usr/local/bin/viptocoin-cli -datadir=/var/lib/.viptocoin/ listtransactions "*" 99999 | jq -r '.[] | select(.category != "send") | select(.amount < .0001) | .txid' | uniq >txid.txt

	while read line; do
	        echo $line 
	        /usr/local/bin/viptocoin-cli -datadir=/var/lib/.viptocoin/ removeprunedfunds $(echo $line)
	done < "txid.txt"
;;

*)
    echo -e $usage
;;	

esac
